CREATE DATABASE IF NOT EXISTS DE1;
USE DE1;

CREATE TABLE IF NOT EXISTS `campaign` (
  `id` varchar(50) NOT NULL,
  `created_by` varchar(50) DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  `last_modified_by` varchar(50) DEFAULT NULL,
  `last_modified_date` datetime DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT NULL,
  `campaign_name` varchar(100) DEFAULT NULL,
  `budget_total` decimal(19,2) DEFAULT NULL,
  `unit_budget` varchar(10) DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `close_date` date DEFAULT NULL,
  `campaign_status` varchar(50) DEFAULT NULL,
  `background_status` varchar(50) DEFAULT NULL,
  `pacing_unit` varchar(50) DEFAULT NULL,
  `company_id` varchar(50) DEFAULT NULL,
  `number_of_pacing` int DEFAULT NULL,
  `recommend_budget` decimal(19,2) DEFAULT NULL,
  `import_xml_url` varchar(255) DEFAULT NULL,
  `bid_set` varchar(50) DEFAULT NULL,
  `ats_type` varchar(50) DEFAULT NULL,
  `ats_data` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `job` (
  `id` int NOT NULL,
  `created_by` varchar(50) DEFAULT NULL,
  `created_date` varchar(50) DEFAULT NULL,
  `last_modified_by` varchar(50) DEFAULT NULL,
  `last_modified_date` varchar(50) DEFAULT NULL,
  `is_active` int DEFAULT NULL,
  `title` varchar(50) DEFAULT NULL,
  `description` varchar(5000) DEFAULT NULL,
  `work_schedule` varchar(50) DEFAULT NULL,
  `radius_unit` varchar(50) DEFAULT NULL,
  `location_state` varchar(50) DEFAULT NULL,
  `location_list` varchar(50) DEFAULT NULL,
  `role_location` varchar(50) DEFAULT NULL,
  `resume_option` varchar(50) DEFAULT NULL,
  `budget` int DEFAULT NULL,
  `status` int DEFAULT NULL,
  `error` varchar(5000) DEFAULT NULL,
  `template_question_id` int DEFAULT NULL,
  `template_question_name` varchar(50) DEFAULT NULL,
  `question_form_description` varchar(50) DEFAULT NULL,
  `redirect_url` varchar(256) DEFAULT NULL,
  `start_date` varchar(50) DEFAULT NULL,
  `end_date` varchar(50) DEFAULT NULL,
  `close_date` varchar(50) DEFAULT NULL,
  `group_id` int DEFAULT NULL,
  `minor_id` int DEFAULT NULL,
  `campaign_id` int DEFAULT NULL,
  `company_id` int DEFAULT NULL,
  `history_status` int DEFAULT NULL,
  `ref_id` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `company` (
  `id` int NOT NULL,
  `created_by` varchar(50) DEFAULT NULL,
  `created_date` varchar(50) DEFAULT NULL,
  `last_modified_by` varchar(50) DEFAULT NULL,
  `last_modified_date` varchar(50) DEFAULT NULL,
  `is_active` int DEFAULT NULL,
  `name` varchar(50) DEFAULT NULL,
  `is_agree_conditon` int DEFAULT NULL,
  `is_agree_sign_deal` int DEFAULT NULL,
  `sign_deal_user` varchar(50) DEFAULT NULL,
  `billing_id` int DEFAULT NULL,
  `manage_type` int DEFAULT NULL,
  `customer_type` int DEFAULT NULL,
  `status` int DEFAULT NULL,
  `publisher_id` int DEFAULT NULL,
  `flat_rate` varchar(50) DEFAULT NULL,
  `percentage_of_click` varchar(50) DEFAULT NULL,
  `logo` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `events` (
  `job_id` int DEFAULT NULL,
  `dates` varchar(50) DEFAULT NULL,
  `hours` int DEFAULT NULL,
  `disqualified_application` int DEFAULT NULL,
  `qualified_application` int DEFAULT NULL,
  `conversion` int DEFAULT NULL,
  `company_id` int DEFAULT NULL,
  `group_id` int DEFAULT NULL,
  `campaign_id` int DEFAULT NULL,
  `publisher_id` int DEFAULT NULL,
  `bid_set` int DEFAULT NULL,
  `clicks` int DEFAULT NULL,
  `impressions` varchar(50) DEFAULT NULL,
  `spend_hour` int DEFAULT NULL,
  `sources` varchar(50) DEFAULT NULL,
  `updated_at` DATETIME DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `master_publisher` (
  `id` int NOT NULL,
  `created_by` varchar(50) DEFAULT NULL,
  `created_date` varchar(50) DEFAULT NULL,
  `last_modified_by` varchar(50) DEFAULT NULL,
  `last_modified_date` varchar(50) DEFAULT NULL,
  `is_active` int DEFAULT NULL,
  `publisher_name` varchar(50) DEFAULT NULL,
  `email` varchar(50) DEFAULT NULL,
  `access_token` varchar(50) DEFAULT NULL,
  `publisher_type` int DEFAULT NULL,
  `publisher_status` int DEFAULT NULL,
  `publisher_frequency` int DEFAULT NULL,
  `curency` int DEFAULT NULL,
  `time_zone` varchar(50) DEFAULT NULL,
  `cpc_increment` int DEFAULT NULL,
  `bid_reading` int DEFAULT NULL,
  `min_bid` int DEFAULT NULL,
  `max_bid` int DEFAULT NULL,
  `countries` varchar(50) DEFAULT NULL,
  `data_sharing` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SELECT 'MySQL schema created successfully!' as status;